public class mycalss
 {
            public mycalss()
            {
            
                System.debug('hello Constructure');
                
            }
            
            
            //declaration of a methods
            //method 1
            public void sayhell()
            {
                System.debug('hello......');
            }
            
            //method 2
            public void saybye()
            {
                System.debug('Bye......');
            }
            
            
 
 }